line.bot:
  channel-token: '9q2HnGYMamyAHBEku7u3pLGNfhrjGdaoqGhVjElnL0GCYUydxQ/oESLayC6tRl2cGBPRSDSQWZ+dVBDuFwe+4Vu+8CcCZZ2+6W5E8iYvTAjS34kMsaKGVlUIM67HZpB25KGPMeYPbbzVpORWgqrW6wdB04t89/1O/w1cDnyilFU='
  channel-secret: '5a4e09ac63ebd675659dcb29fa63826f'
  handler.path: /callback

#spring.jpa.hibernate.ddl-auto=update
spring:
  datasource:
    #url: jdbc:mariadb://p2d0untihotgr5f6.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/x4b3jdswpr8bw7jw
    url: jdbc:mariadb://127.0.0.1:3306/x4b3jdswpr8bw7jw
    #username: ouenzxiu8mljdite
    username: root
    #password: lkaisp18z363xnsf
    password: P@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
azure:
  subscription.key: 17c91ddddd45477aa6a723d3ea4bc76a
  cognitive.uri: https://westcentralus.api.cognitive.microsoft.com/vision/v2.0/analyze?visualFeatures=Categories&language=en