line.bot:
  channel-token: '9q2HnGYMamyAHBEku7u3pLGNfhrjGdaoqGhVjElnL0GCYUydxQ/oESLayC6tRl2cGBPRSDSQWZ+dVBDuFwe+4Vu+8CcCZZ2+6W5E8iYvTAjS34kMsaKGVlUIM67HZpB25KGPMeYPbbzVpORWgqrW6wdB04t89/1O/w1cDnyilFU='
  channel-secret: '5a4e09ac63ebd675659dcb29fa63826f'
  handler.path: /callback