line.bot:
  channel-token: 'o9Uv1sms4JLPzqYTY5MxC0kluLNbKKgRcXVO9obDvtx8a5sAWs/KK2b0sisWY1RnKsvjSw65vO+weWFt7Sr2XqoG85exKGbBmIc4+0P0PTheu0Ncem5G94PwEQCYfy92aBeZNFX6gHGErgHoVMWFtgdB04t89/1O/w1cDnyilFU='
  channel-secret: 'f0f8087e94c27fadac965e008b97d86e'
  handler.path: /callback

#spring.jpa.hibernate.ddl-auto=update
spring:
  datasource:
    #url: jdbc:mariadb://p2d0untihotgr5f6.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/x4b3jdswpr8bw7jw
    url: jdbc:mariadb://127.0.0.1:3306/x4b3jdswpr8bw7jw
    #username: ouenzxiu8mljdite
    username: root
    #password: lkaisp18z363xnsf
    password: P@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect  